/*
 * This source file was generated by the Gradle 'init' task
 */
package org.commuter_notifier;

import com.google.gson.Gson;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import java.time.ZoneId;
import java.time.LocalDateTime;

import java.util.List;
import java.util.Map;

public class App {
    private static final String LAT = "51.49";
    private static final String LON = "-0.04";
    private static final String FORECAST_MODE = "minutely_15";
    private static final String FORECAST_VARS = "temperature_2m,precipitation_probability,precipitation";
    private static final ZoneId TZ = ZoneId.of(System.getenv().getOrDefault("APP_TIMEZONE", "Europe/London"));
    private static final int FORECAST_HOURS = 2;

    public record Minutely15Forecast(
        List<Double> temperature_2m,
        List<Integer> precipitation_probability,
        List<Double> precipitation
    ) {};

    public record OpenMeteoForecast(
        Minutely15Forecast minutely_15
    ) {};

    public static void main(String[] args) throws Exception{
        String request_url = "https://api.open-meteo.com/v1/forecast?"
                            + "latitude=" + LAT
                            + "&longitude=" + LON
                            + "&" + FORECAST_MODE + "=" + FORECAST_VARS
                            + "&timezone=" + TZ
                            + "&forecast_minutely_15=" + FORECAST_HOURS * 4;

        System.out.println("Request UREL: " + request_url);
        HttpClient client = HttpClient.newHttpClient();

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(request_url))
                .GET()
                .build();

        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        OpenMeteoForecast forecast = new Gson().fromJson(response.body(), OpenMeteoForecast.class);
        System.out.println(forecast.minutely_15().temperature_2m());
    }
}
