/*
 * This source file was generated by the Gradle 'init' task
 */
package org.commuter_notifier;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        assert true;
    }
}
